name: seniorproject
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1
environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  table_calendar: ^3.0.0
  image_picker: ^1.0.7
  permission_handler: ^11.0.1
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_core_platform_interface: ^5.0.0
  firebase_storage: ^11.6.10


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/designs/images/rectangle-32.png
    - assets/designs/images/ellipse-18-bg.png
    - assets/slides/images/main-card-bg-bg.png
    - assets/slides/images/iconly-bold-time-square.png
    - assets/slides/images/wifi.png
    - assets/slides/images/ellipse-18-bg-pkT.png
    - assets/slides/images/calendar.png
    - assets/slides/images/rectangle-4199.png
    - assets/slides/images/time-circle.png
    - assets/slides/images/rectangle-4199-3Es.png
    - assets/slides/images/rectangle-32-5wZ.png
    - assets/designs/images/pmulogo.png
    - assets/slides/images/rectangle-4199-cH1.png
    - assets/slides/images/vector-3DD.png
    - assets/slides/images/calendar-9L7.png
    - assets/slides/images/main-card-bg-bg-qTq.png
    - assets/slides/images/line-1.png
    - assets/slides/images/main-card-bg-bg-B95.png
    - assets/slides/images/eva-arrow-ios-forward-outline.png
    - assets/slides/images/iconly-bold-calendar.png
    - assets/slides/images/battery-TkX.png
    - assets/slides/images/main-card-bg-bg-opP.png
    - assets/slides/images/group-7aB.png
    - assets/slides/images/group-oUP.png
    - assets/slides/images/image-6-9HM.png
    - assets/slides/images/main-card-bg-bg-Vs1.png
    - assets/slides/images/iconly-bold-calendar-6Us.png
    - assets/slides/images/vector-akb.png
    - assets/slides/images/wifi-S27.png
    - assets/slides/images/group-6.png
    - assets/designs/images/time-circle-hMV.png
    - assets/designs/images/calendar-wBZ.png
    - assets/slides/images/time-circle-UBV.png
    - assets/slides/images/time-circle-Mm5.png
    - assets/slides/images/time-circle-sMM.png
    - assets/slides/images/fluent-home-28-filled-1iT.png
    - assets/slides/images/fluent-home-28-filled-kR9.png
    - assets/slides/images/cellular-connection-rDH.png
    - assets/slides/images/vector-R1V.png
    - assets/slides/images/ellipse-18-bg-KMm.png
    - assets/slides/images/wifi-gTD.png
    - assets/slides/images/cellular-connection-Ejd.png
    - assets/slides/images/main-card-bg-bg-d15.png
    - assets/slides/images/iconly-bold-calendar-Xs9.png
    - assets/slides/images/cellular-connection-Tko.png
    - assets/slides/images/iconly-bold-time-circle.png
    - assets/slides/images/time-circle-zfM.png
    - assets/slides/images/fluent-home-28-filled-rgB.png
    - assets/slides/images/image-6-3sq.png
    - assets/slides/images/map-pin.png
    - assets/slides/images/time-circle-Cno.png
    - assets/slides/images/time-circle-JL3.png
    - assets/slides/images/eva-arrow-ios-forward-outline-qas.png
    - assets/slides/images/rectangle-35.png
    - assets/slides/images/map-pin-W7u.png
    - assets/slides/images/vector-sUF.png
    - assets/designs/images/rectangle-35-4ew.png
    - assets/slides/images/rectangle-32-L4b.png
    - assets/slides/images/rectangle-35-6dR.png
    - assets/designs/images/rectangle-4204-bg.png
    - assets/designs/images/rectangle-4204-bg-mmu.png
    - assets/designs/images/rectangle-4199-CiF.png
    - assets/designs/images/rectangle-4199-Q5Z.png
    - assets/designs/images/rectangle-35-teo.png
    - assets/designs/images/eva-arrow-ios-forward-outline-v4s.png
    - assets/designs/images/calendar-kWX.png
    - assets/designs/images/vector-gjD.png
    - assets/designs/images/rectangle-32-ZPZ.png
    - assets/designs/images/ellipse-2-bg-wxf.png
    - assets/designs/images/ellipse-19-bg.png
    - assets/designs/images/ellipse-15-bg.png
    - assets/designs/images/ellipse-18-bg-Tmu.png
    - assets/designs/images/ellipse-17-bg.png
    - assets/designs/images/ellipse-16-bg.png
    - assets/designs/images/ellipse-20-bg.png
    - assets/designs/images/rectangle-4199-S9y.png
    - assets/designs/images/line-2.png
    - assets/designs/images/auto-group-nzb1.png
    - assets/designs/images/ellipse-18-bg-MLw.png
    - assets/designs/images/smarthomes.png
    - assets/designs/images/triangle.png
    - assets/designs/images/star.png
    - assets/designs/images/line-2-aZ1.png
    - assets/designs/images/star-9s1.png
    - assets/designs/images/emoji-rocket.png
    - assets/designs/images/fluent-location-12-filled.png
    - assets/designs/images/group-15-CbD.png
    - assets/designs/images/material-symbols-pending-actions-rounded-mgw.png
    - assets/designs/images/time-circle-qkf.png
    - assets/designs/images/emoji-white-heavy-check-mark.png
    - assets/designs/images/vector-vaP.png
    - assets/designs/images/material-symbols-pending-actions-rounded-Pmd.png
    - assets/designs/images/vector-yDu.png
    - assets/designs/images/line-1-fGw.png
    - assets/designs/images/time-circle-ibu.png
    - assets/designs/images/emoji-postbox.png
    - assets/designs/images/ellipse-2-rNf.png
    - assets/designs/images/auto-group-6mcp.png
    - assets/designs/images/rectangle-35-bgF.png
    - assets/designs/images/time-circle-VUP.png
    - assets/designs/images/ellipse-18-bg-2zf.png
    - assets/designs/images/ellipse-2-bg.png
    - assets/designs/images/cybersecurityevent.png
    - assets/designs/images/chatgpt.png
    - assets/designs/images/Finance.png
    - assets/designs/images/Beach.png
    - assets/designs/images/f-workshop.png
    - assets/designs/images/financial.png
    - assets/designs/images/Rwad.png
    - assets/designs/images/Samaa.png
    - assets/designs/images/Talk.png
    - assets/designs/images/MIS.png
    - assets/designs/images/MISWS.png
    - assets/designs/images/MIS2.png
    - assets/designs/images/talk2.png
    - assets/designs/images/Pmuwinter.png
    - assets/designs/images/robotics.png
    - assets/designs/images/chatbox.png
    - assets/designs/images/My-Event-logo.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
